apiVersion: v1
kind: Service
metadata:
  name: postgres-kooplex-prod
  namespace: kooplex-veo
spec:
  ports:
    - name: port-prod
      protocol: TCP
      port: 5433
      targetPort: 5432
  selector:
    app: app-prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-kooplex-prod
  namespace: kooplex-veo
spec:
  serviceName: "postgres"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: app-prod
  template:
    metadata:
      labels:
        app: app-prod
    spec:
      containers:
      - name: postgres-prod
        image: postgres:11.12
        ports:
          - containerPort: 5433
            name: port-prod
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-admin-ebi
              key: adminpw
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-admin-ebi
              key: admin
        - name: PGDATA
          value: /var/lib/postgresql/data_prod
        volumeMounts:
        - name: nfs
          mountPath: /var/lib/postgresql/data_prod
          subPath: prod
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-postgres-ssd
