---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-ssd
  namespace: kooplex-veo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10T
  storageClassName: example-nfs
