---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-raw-ssd
  namespace: kooplex-veo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: example-nfs
