CREATE TABLE IF NOT EXISTS vcf (
    ena_run     text,       -- ENA ID
    chrom       text,
    pos         int,
    ref         text,
    alt         text,
    qual         int,
    filter      text,
    dp         int,
    af         real,
    sb         int,
    count_ref_forward_base      int,
    count_ref_reverse_base      int,
    count_alt_forward_base      int,
    count_alt_reverse_base      int,
    hrun         int,
    indel      boolean,
    lof      text,
    nmd      text,
    major      int,
    ann_num      int,
    annotation      text,
    annotation_impact text,
    gene_name      text,
    gene_id      text,
    feature_type      text,
    feature_id     text,
    transcript_biotype      text,
    rank_      text,
    hgvs_c      text,
    hgvs_p      text,
    cdna_pos__cdna_length      text,
    cds_pos__cds_length      text,
    aa_pos__aa_length      text,
    distance         int,
    errors_warnings_info      text
);
